version: '3.4'

services:
  bot:
    extends:
      file: secret.yml
      service: bot
    image: abome40k/nt-bot
    hostname: nt-bot
    container_name: nt-bot
    restart: on-failure
    command: python ./nt-bot/src/nt-bot.py
    build:
      context: .
      dockerfile: .\dockerfile